apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lab28-api
  namespace: lab28
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: lab28-api
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              gateway.networking.k8s.io/gateway-controller: envoy-gateway
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: lab28
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
